/* tslint:disable */
/* eslint-disable */
/**
 * Taskbook API
 * API for a sample project which randomly mixes Kotlin and Java classes to show the interoperability capabilities. Also includes openapi client generation for a Vue3 UI
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TaskDto } from './task-dto';

/**
 * 
 * @export
 * @interface PaginatedTaskDto
 */
export interface PaginatedTaskDto {
    /**
     * 
     * @type {Array<TaskDto>}
     * @memberof PaginatedTaskDto
     */
    'content'?: Array<TaskDto>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTaskDto
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTaskDto
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTaskDto
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTaskDto
     */
    'totalElements'?: number;
}

